stages:
  download_and_unpack:
    cmd:
      mkdir -p data/ && tar -zxvf tibia854.tgz -C data/
      --strip-components=1 Tibia/Tibia.dat Tibia/Tibia.pic Tibia/Tibia.spr
    deps:
    - tibia854.tgz
    outs:
    - data/Tibia.dat
    - data/Tibia.pic
    - data/Tibia.spr
