#ifndef PRODUCTNAME
#define PRODUCTVERSION "0.2.1SVN"
#define PRODUCTSHORT "YATC"
#define PRODUCTLONG "YATC - Yet Another Tibia Client"
#define PRODUCTNAME PRODUCTSHORT " v" PRODUCTVERSION
#define PRODUCTLONGNAME PRODUCTLONG " version " PRODUCTVERSION
#endif
