Document: yatc
Title: Debian yatc Manual
Author: <insert document author here>
Abstract: This manual describes what yatc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yatc/yatc.sgml.gz

Format: postscript
Files: /usr/share/doc/yatc/yatc.ps.gz

Format: text
Files: /usr/share/doc/yatc/yatc.text.gz

Format: HTML
Index: /usr/share/doc/yatc/html/index.html
Files: /usr/share/doc/yatc/html/*.html

  
